[world]
description = "jokers_of_neon_profile"
name = "jokers_of_neon_profile"
seed = "jokers_of_neon_profile"

[namespace]
default = "jokers_of_neon_profile7"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245"
private_key = "0x06c3f4d5e62d4b873a1389cec6671a9ef3414af6321d893bdf3967bc9c77fa47"

[writers]
"jokers_of_neon_profile7" = [
    "jokers_of_neon_profile7-profile_system",
    "jokers_of_neon_profile7-pack_system",
    "jokers_of_neon_profile7-xp_system",
    "jokers_of_neon_profile7-season_system",
]

[init_call_args]
"jokers_of_neon_profile7-profile_system" = [
    "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245",
]
"jokers_of_neon_profile7-xp_system" = [
    "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245",
]
"jokers_of_neon_profile7-season_system" = [
    "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245",
]
