[world]
description = "jokers_of_neon_profile"
name = "jokers_of_neon_profile"
seed = "jokers_of_neon_profile"

[namespace]
default = "jokers_of_neon_profile9"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x3c2c6f73bc088d83c96edcf46854a60f256a7cd58a350904cef5716d4a800a1"
private_key = "0x0291db342f82b9e9aebdcc9c6251f28fa5fd622ca872d494da957fb99c6e4e7b"

[writers]
"jokers_of_neon_profile9" = [
    "jokers_of_neon_profile9-profile_system",
    "jokers_of_neon_profile9-xp_system",
    "jokers_of_neon_profile9-season_system",
]

[init_call_args]
"jokers_of_neon_profile9-profile_system" = [
    "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245",
]
"jokers_of_neon_profile9-xp_system" = [
    "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245",
]
"jokers_of_neon_profile9-season_system" = [
    "0x00dba4d5ba495338b74aceac92ddc26afff9319d675e09db0aadba40cc606245",
]
