[package]
cairo-version = "2.13.1"
name = "jokers_of_neon_profile"
version = "1.5.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"                      # scarb run migrate
spawn = "sozo execute dojo_starter-actions spawn --wait"    # scarb run spawn
move = "sozo execute dojo_starter-actions move -c 1 --wait" # scarb run move

[dependencies]
dojo = "1.8.0"
dojo_cairo_macros = "1.8.0"
starknet = "2.13.1"
jokers_of_neon_lib = { git = "https://github.com/caravana-studio/jokers-of-neon-lib", branch="develop" }
openzeppelin_introspection = "1.0.0"
openzeppelin_access = "1.0.0"

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "jokers_of_neon_lib::models::external::profile::m_Profile",
    "jokers_of_neon_lib::models::external::profile::m_PlayerStats",
    "jokers_of_neon_lib::models::external::profile::m_ProfileLevelConfig",
    "jokers_of_neon_lib::random::m_Random",
]

[dev-dependencies]
cairo_test = "=2.13.1"
dojo_cairo_test = "1.8.0"

[profile.slot]
[profile.testnet]
[profile.mainnet]

[lib]
